### ISSUE TITLE
Upgrade to Bootstrap 5 version

### ISSUE THREAD

**Issue by EvanCarroll** [lopes/zola.386#17]
According to @kristopolous the new version of BOOTSTRA.386 isn't bootstrap2, seems it's up to bootstrap5. Maybe we can get an upgrade?

https://github.com/kristopolous/BOOTSTRA.386/tree/master/v5.3.1

**Comment by kristopolous** [comment]
it's way not done yet. if you're happy with 2 stick with 2.
